// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddContractAssetRequest {
    /// The contract's address (or xpub) of the wallet
    #[serde(rename = "address")]
    pub address: String,
    /// The destination tag, for XRP wallets
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
}

impl AddContractAssetRequest {
    pub fn new(address: String) -> AddContractAssetRequest {
        AddContractAssetRequest { address, tag: None }
    }
}
