// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssetMetadata {
    /// The scope of the asset
    #[serde(rename = "scope")]
    pub scope: Scope,
    /// Is asset deprecated
    #[serde(rename = "deprecated")]
    pub deprecated: bool,
}

impl AssetMetadata {
    pub fn new(scope: Scope, deprecated: bool) -> AssetMetadata {
        AssetMetadata { scope, deprecated }
    }
}
/// The scope of the asset
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scope {
    #[serde(rename = "Global")]
    Global,
    #[serde(rename = "Local")]
    Local,
}

impl Default for Scope {
    fn default() -> Scope {
        Self::Global
    }
}
