/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChainInfoResponseDto {
    /// The protocol identifier (e.g. \"ETH\"/\"SOL\").
    #[serde(rename = "chainDescriptor")]
    pub chain_descriptor: String,
    /// The current epoch number of the blockchain network.
    #[serde(rename = "currentEpoch")]
    pub current_epoch: f64,
    /// The percentage of time that has elapsed within the current epoch, represented as a decimal value between 0 and 1.
    #[serde(rename = "epochElapsed")]
    pub epoch_elapsed: f64,
    /// The total duration in milliseconds of a single epoch.
    #[serde(rename = "epochDuration")]
    pub epoch_duration: f64,
    /// Additional information related to the blockchain. This may include extra details about the blockchain network.
    #[serde(rename = "additionalInfo")]
    pub additional_info: models::AdditionalInfoDto,
}

impl ChainInfoResponseDto {
    pub fn new(chain_descriptor: String, current_epoch: f64, epoch_elapsed: f64, epoch_duration: f64, additional_info: models::AdditionalInfoDto) -> ChainInfoResponseDto {
        ChainInfoResponseDto {
            chain_descriptor,
            current_epoch,
            epoch_elapsed,
            epoch_duration,
            additional_info,
        }
    }
}

