// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

///
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChainDescriptor {
    #[serde(rename = "ETH")]
    Eth,
    #[serde(rename = "SOL")]
    Sol,
    #[serde(rename = "MATIC")]
    Matic,
    #[serde(rename = "ETH_TEST6")]
    EthTest6,
    #[serde(rename = "SOL_TEST")]
    SolTest,
}

impl std::fmt::Display for ChainDescriptor {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Eth => write!(f, "ETH"),
            Self::Sol => write!(f, "SOL"),
            Self::Matic => write!(f, "MATIC"),
            Self::EthTest6 => write!(f, "ETH_TEST6"),
            Self::SolTest => write!(f, "SOL_TEST"),
        }
    }
}

impl Default for ChainDescriptor {
    fn default() -> ChainDescriptor {
        Self::Eth
    }
}
