/*
 * Fireblocks API
 *
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.8.0
 * Contact: developers@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigOperationStatus {
    #[serde(rename = "PENDING")]
    Pending,
    #[serde(rename = "VALIDATION_IN_PROGRESS")]
    ValidationInProgress,
    #[serde(rename = "READY_FOR_EXECUTION")]
    ReadyForExecution,
    #[serde(rename = "VALIDATION_FAILED")]
    ValidationFailed,

}

impl std::fmt::Display for ConfigOperationStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Pending => write!(f, "PENDING"),
            Self::ValidationInProgress => write!(f, "VALIDATION_IN_PROGRESS"),
            Self::ReadyForExecution => write!(f, "READY_FOR_EXECUTION"),
            Self::ValidationFailed => write!(f, "VALIDATION_FAILED"),
        }
    }
}

impl Default for ConfigOperationStatus {
    fn default() -> ConfigOperationStatus {
        Self::Pending
    }
}

