/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePayoutRequest {
    #[serde(rename = "paymentAccount")]
    pub payment_account: models::PaymentAccount,
    #[serde(rename = "instructionSet")]
    pub instruction_set: Vec<models::PayoutInstruction>,
}

impl CreatePayoutRequest {
    pub fn new(payment_account: models::PaymentAccount, instruction_set: Vec<models::PayoutInstruction>) -> CreatePayoutRequest {
        CreatePayoutRequest {
            payment_account,
            instruction_set,
        }
    }
}

