// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMultipleVaultAccountsJobStatus {
    #[serde(rename = "status")]
    pub status: String,
    /// Mapping between VaultAccountId to a mapping of asset to address
    #[serde(rename = "vaultAccounts", skip_serializing_if = "Option::is_none")]
    pub vault_accounts:
        Option<std::collections::HashMap<String, std::collections::HashMap<String, String>>>,
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
}

impl CreateMultipleVaultAccountsJobStatus {
    pub fn new(status: String) -> CreateMultipleVaultAccountsJobStatus {
        CreateMultipleVaultAccountsJobStatus {
            status,
            vault_accounts: None,
            error_message: None,
        }
    }
}
