/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DisbursementOperationPreview {
    #[serde(rename = "input")]
    pub input: models::DisbursementOperationInput,
    #[serde(rename = "output", skip_serializing_if = "Option::is_none")]
    pub output: Option<models::DisbursementOperationPreviewOutput>,
    #[serde(rename = "failure", skip_serializing_if = "Option::is_none")]
    pub failure: Option<models::OperationExecutionFailure>,
}

impl DisbursementOperationPreview {
    pub fn new(input: models::DisbursementOperationInput) -> DisbursementOperationPreview {
        DisbursementOperationPreview {
            input,
            output: None,
            failure: None,
        }
    }
}

