/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DraftResponse : Response object for draft operations
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DraftResponse {
    /// Operation status
    #[serde(rename = "status")]
    pub status: String,
    /// Draft rules
    #[serde(rename = "rules")]
    pub rules: Vec<models::PolicyRule>,
    /// Draft unique id
    #[serde(rename = "draftId")]
    pub draft_id: String,
    #[serde(rename = "metadata")]
    pub metadata: models::PolicyMetadata,
}

impl DraftResponse {
    /// Response object for draft operations
    pub fn new(status: String, rules: Vec<models::PolicyRule>, draft_id: String, metadata: models::PolicyMetadata) -> DraftResponse {
        DraftResponse {
            status,
            rules,
            draft_id,
            metadata,
        }
    }
}

