/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DropTransactionResponse {
    #[serde(rename = "txStatus", skip_serializing_if = "Option::is_none")]
    pub tx_status: Option<String>,
    #[serde(rename = "txId", skip_serializing_if = "Option::is_none")]
    pub tx_id: Option<String>,
    #[serde(rename = "replacedTxHash", skip_serializing_if = "Option::is_none")]
    pub replaced_tx_hash: Option<String>,
}

impl DropTransactionResponse {
    pub fn new() -> DropTransactionResponse {
        DropTransactionResponse {
            tx_status: None,
            tx_id: None,
            replaced_tx_hash: None,
        }
    }
}

