/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExchangeAccountsPaged {
    #[serde(rename = "ExchangeAccount", skip_serializing_if = "Option::is_none")]
    pub exchange_account: Option<Vec<models::ExchangeAccount>>,
    #[serde(rename = "paging", skip_serializing_if = "Option::is_none")]
    pub paging: Option<models::ExchangeAccountsPagedPaging>,
    #[serde(rename = "prevUrl", skip_serializing_if = "Option::is_none")]
    pub prev_url: Option<String>,
    #[serde(rename = "nextUrl", skip_serializing_if = "Option::is_none")]
    pub next_url: Option<String>,
}

impl ExchangeAccountsPaged {
    pub fn new() -> ExchangeAccountsPaged {
        ExchangeAccountsPaged {
            exchange_account: None,
            paging: None,
            prev_url: None,
            next_url: None,
        }
    }
}

