// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// FeeInfo : Details of the transaction's fee.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeInfo {
    /// The fee paid to the network
    #[serde(rename = "networkFee", skip_serializing_if = "Option::is_none")]
    pub network_fee: Option<String>,
    /// The total fee deducted by the exchange from the actual requested amount
    /// (serviceFee = amount - netAmount)
    #[serde(rename = "serviceFee", skip_serializing_if = "Option::is_none")]
    pub service_fee: Option<String>,
    #[serde(rename = "gasPrice", skip_serializing_if = "Option::is_none")]
    pub gas_price: Option<String>,
}

impl FeeInfo {
    /// Details of the transaction's fee.
    pub fn new() -> FeeInfo {
        FeeInfo {
            network_fee: None,
            service_fee: None,
            gas_price: None,
        }
    }
}
