/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetSmartTransferUserGroups200Response {
    /// Success message
    #[serde(rename = "message", deserialize_with = "Option::deserialize")]
    pub message: Option<String>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<models::SmartTransferUserGroupsDto>,
}

impl GetSmartTransferUserGroups200Response {
    pub fn new(message: Option<String>) -> GetSmartTransferUserGroups200Response {
        GetSmartTransferUserGroups200Response {
            message,
            data: None,
        }
    }
}

