/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOwnedTokens200Response {
    #[serde(rename = "paging", skip_serializing_if = "Option::is_none")]
    pub paging: Option<models::Paging>,
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Vec<models::TokenResponse>>,
}

impl ListOwnedTokens200Response {
    pub fn new() -> ListOwnedTokens200Response {
        ListOwnedTokens200Response {
            paging: None,
            data: None,
        }
    }
}

