// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifySigningKeyAgentIdDto {
    /// Id of user that represent agent servers which signs with the key
    #[serde(rename = "agentUserId")]
    pub agent_user_id: String,
}

impl ModifySigningKeyAgentIdDto {
    pub fn new(agent_user_id: String) -> ModifySigningKeyAgentIdDto {
        ModifySigningKeyAgentIdDto { agent_user_id }
    }
}
