// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewAddress {
    /// The address string.
    #[serde(rename = "address")]
    pub address: String,
    /// The index of the address in the list.
    #[serde(rename = "index")]
    pub index: i32,
    /// A description of the address.
    #[serde(rename = "description")]
    pub description: String,
}

impl NewAddress {
    pub fn new(address: String, index: i32, description: String) -> NewAddress {
        NewAddress {
            address,
            index,
            description,
        }
    }
}
