// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NoneNetworkRoutingDest {
    /// No network routing logic.
    #[serde(rename = "scheme")]
    pub scheme: Scheme,
}

impl NoneNetworkRoutingDest {
    pub fn new(scheme: Scheme) -> NoneNetworkRoutingDest {
        NoneNetworkRoutingDest { scheme }
    }
}
/// No network routing logic.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scheme {
    #[serde(rename = "NONE")]
    None,
}

impl Default for Scheme {
    fn default() -> Scheme {
        Self::None
    }
}
