/*
 * Fireblocks API
 *
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.8.0
 * Contact: developers@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PolicyRuleSrc : Defines source accounts the rule allows transfers to originate from
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyRuleSrc {
    /// A set of ids in a tuple format
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<Vec<models::SrcOrDestAttributesInner>>>,
}

impl PolicyRuleSrc {
    /// Defines source accounts the rule allows transfers to originate from
    pub fn new() -> PolicyRuleSrc {
        PolicyRuleSrc {
            ids: None,
        }
    }
}

