/*
 * Fireblocks API
 *
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.8.0
 * Contact: developers@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PolicyValidation : Policy validation object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyValidation {
    /// Validation status
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "checkResult")]
    pub check_result: models::PolicyCheckResult,
}

impl PolicyValidation {
    /// Policy validation object
    pub fn new(status: String, check_result: models::PolicyCheckResult) -> PolicyValidation {
        PolicyValidation {
            status,
            check_result,
        }
    }
}

