/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PolicyRuleDst : Defines the destination accounts the rule allows transfers to
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PolicyRuleDst {
    /// A set of ids in a tuple format
    #[serde(rename = "ids", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Vec<models::PolicyRuleSrcIdsInner>>,
}

impl PolicyRuleDst {
    /// Defines the destination accounts the rule allows transfers to
    pub fn new() -> PolicyRuleDst {
        PolicyRuleDst {
            ids: None,
        }
    }
}

