// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RegisterNewAssetRequest {
    /// Native asset of blockchain
    #[serde(rename = "blockchainId")]
    pub blockchain_id: String,
    /// Asset address. - EVM-based chains: token contract address - Stellar
    /// (XLM): issuer address - Algorand (ALGO): asset ID - TRON (TRX): token
    /// contract address - NEAR: token address - Solana: token's mint account
    /// address
    #[serde(rename = "address")]
    pub address: String,
    /// Asset symbol
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
}

impl RegisterNewAssetRequest {
    pub fn new(blockchain_id: String, address: String) -> RegisterNewAssetRequest {
        RegisterNewAssetRequest {
            blockchain_id,
            address,
            symbol: None,
        }
    }
}
