// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResendNotificationsByResourceIdRequest {
    /// The resource id to resend notifications for
    #[serde(rename = "resourceId")]
    pub resource_id: uuid::Uuid,
    /// (optional) List of notification statuses to exclude from the resend
    /// operation     - Empty array means all statuses will be included     - If
    /// you want to exclude some statuses, you can use the following example: [
    /// IN_PROGRESS, FAILED ]     - Default if missing, means all statuses other
    /// than \"COMPLETED\" will be included
    #[serde(rename = "excludeStatuses", skip_serializing_if = "Option::is_none")]
    pub exclude_statuses: Option<Vec<models::NotificationStatus>>,
}

impl ResendNotificationsByResourceIdRequest {
    pub fn new(resource_id: uuid::Uuid) -> ResendNotificationsByResourceIdRequest {
        ResendNotificationsByResourceIdRequest {
            resource_id,
            exclude_statuses: None,
        }
    }
}
