/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SetOtaStatusRequest {
    /// Set true or false to enable or disable One Time Address (OTA)
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
}

impl SetOtaStatusRequest {
    pub fn new() -> SetOtaStatusRequest {
        SetOtaStatusRequest {
            enable: None,
        }
    }
}

