/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StakeRequestDto {
    /// The source vault account to stake from
    #[serde(rename = "vaultAccountId")]
    pub vault_account_id: String,
    /// The ID of the provider
    #[serde(rename = "providerId")]
    pub provider_id: String,
    /// Amount of tokens to stake
    #[serde(rename = "stakeAmount")]
    pub stake_amount: String,
    /// The note to associate with the stake transactions.
    #[serde(rename = "txNote", skip_serializing_if = "Option::is_none")]
    pub tx_note: Option<String>,
    /// Represents the fee for a transaction, which can be specified as a percentage value. Only one of fee/feeLevel is required.
    #[serde(rename = "fee", skip_serializing_if = "Option::is_none")]
    pub fee: Option<String>,
    /// Represents the fee level for a transaction, which can be set as slow, medium, or fast. Only one of fee/feeLevel is required.
    #[serde(rename = "feeLevel", skip_serializing_if = "Option::is_none")]
    pub fee_level: Option<String>,
}

impl StakeRequestDto {
    pub fn new(vault_account_id: String, provider_id: String, stake_amount: String) -> StakeRequestDto {
        StakeRequestDto {
            vault_account_id,
            provider_id,
            stake_amount,
            tx_note: None,
            fee: None,
            fee_level: None,
        }
    }
}

