// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use serde::{Deserialize, Serialize};

/// TransactionRequestNetworkFee : For EVM-based blockchains only. The total
/// transaction fee in the blockchain’s largest unit. Note: Only two of the
/// three arguments can be specified in a single transaction: `gasLimit`,
/// `gasPrice` and `networkFee`. Fireblocks recommends using a numeric string
/// for accurate precision. Although a number input exists, it is deprecated. -
/// The transaction blockchain fee. - For Ethereum, you can't pass gasPrice,
/// gasLimit and networkFee all together. - A numeric value representation is
/// required. For EVM-based blockchains only. The total transaction fee in the
/// blockchain’s largest unit. Note: Only two of the three arguments can be
/// specified in a single transaction: `gasLimit`, `gasPrice` and `networkFee`.
/// Fireblocks recommends using a numeric string for accurate precision.
/// Although a number input exists, it is deprecated. - The transaction
/// blockchain fee. - For Ethereum, you can't pass gasPrice, gasLimit and
/// networkFee all together. - A numeric value representation is required.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TransactionRequestNetworkFee {
    /// Numeric string (recommended)
    String(String),
    /// Number (deprecated)
    Number(f64),
}

impl Default for TransactionRequestNetworkFee {
    fn default() -> Self {
        Self::String(Default::default())
    }
}
