/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionResponseDestination {
    #[serde(rename = "destination", skip_serializing_if = "Option::is_none")]
    pub destination: Option<models::DestinationTransferPeerPathResponse>,
    /// Address where the asset was transferred.
    #[serde(rename = "destinationAddress", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub destination_address: Option<Option<serde_json::Value>>,
    /// Description of the address.
    #[serde(rename = "destinationAddressDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub destination_address_description: Option<Option<serde_json::Value>>,
    /// The amount to be sent to this destination.
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<String>,
    /// The USD value of the requested amount.
    #[serde(rename = "amountUSD", skip_serializing_if = "Option::is_none")]
    pub amount_usd: Option<String>,
    #[serde(rename = "amlScreeningResult", skip_serializing_if = "Option::is_none")]
    pub aml_screening_result: Option<models::AmlScreeningResult>,
    /// The ID for AML providers to associate the owner of funds with transactions.
    #[serde(rename = "customerRefId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub customer_ref_id: Option<Option<serde_json::Value>>,
    #[serde(rename = "authorizationInfo", skip_serializing_if = "Option::is_none")]
    pub authorization_info: Option<models::AuthorizationInfo>,
}

impl TransactionResponseDestination {
    pub fn new() -> TransactionResponseDestination {
        TransactionResponseDestination {
            destination: None,
            destination_address: None,
            destination_address_description: None,
            amount: None,
            amount_usd: None,
            aml_screening_result: None,
            customer_ref_id: None,
            authorization_info: None,
        }
    }
}

