// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TravelRulePiiIvms {
    #[serde(rename = "fullName", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    #[serde(rename = "dateOfBirth", skip_serializing_if = "Option::is_none")]
    pub date_of_birth: Option<String>,
    #[serde(rename = "placeOfBirth", skip_serializing_if = "Option::is_none")]
    pub place_of_birth: Option<String>,
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address: Option<String>,
    #[serde(
        rename = "identificationNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub identification_number: Option<String>,
    #[serde(rename = "nationality", skip_serializing_if = "Option::is_none")]
    pub nationality: Option<String>,
    #[serde(rename = "countryOfResidence", skip_serializing_if = "Option::is_none")]
    pub country_of_residence: Option<String>,
    #[serde(
        rename = "taxIdentificationNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub tax_identification_number: Option<String>,
    #[serde(rename = "customerNumber", skip_serializing_if = "Option::is_none")]
    pub customer_number: Option<String>,
}

impl TravelRulePiiIvms {
    pub fn new() -> TravelRulePiiIvms {
        TravelRulePiiIvms {
            full_name: None,
            date_of_birth: None,
            place_of_birth: None,
            address: None,
            identification_number: None,
            nationality: None,
            country_of_residence: None,
            tax_identification_number: None,
            customer_number: None,
        }
    }
}
