// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TravelRuleValidatePiiIvms {
    /// Information about the originator of the transaction
    #[serde(rename = "originatorPersons", skip_serializing_if = "Option::is_none")]
    pub originator_persons: Option<Vec<models::TravelRuleValidatePersons>>,
    /// Information about the beneficiary of the transaction
    #[serde(rename = "beneficiaryPersons", skip_serializing_if = "Option::is_none")]
    pub beneficiary_persons: Option<Vec<models::TravelRuleValidatePersons>>,
    /// Beneficiary account number
    #[serde(rename = "accountNumber", skip_serializing_if = "Option::is_none")]
    pub account_number: Option<Vec<String>>,
}

impl TravelRuleValidatePiiIvms {
    pub fn new() -> TravelRuleValidatePiiIvms {
        TravelRuleValidatePiiIvms {
            originator_persons: None,
            beneficiary_persons: None,
            account_number: None,
        }
    }
}
