/*
 * Fireblocks API
 *
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.8.0
 * Contact: developers@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TravelRuleIssuers {
    #[serde(rename = "yearFounded")]
    pub year_founded: models::TravelRuleIssuer,
    #[serde(rename = "isRegulated")]
    pub is_regulated: models::TravelRuleIssuer,
    #[serde(rename = "regulatoryAuthorities")]
    pub regulatory_authorities: models::TravelRuleIssuer,
    #[serde(rename = "name")]
    pub name: models::TravelRuleIssuer,
    #[serde(rename = "logo")]
    pub logo: models::TravelRuleIssuer,
    #[serde(rename = "website")]
    pub website: models::TravelRuleIssuer,
    #[serde(rename = "legalName")]
    pub legal_name: models::TravelRuleIssuer,
    #[serde(rename = "legalStructure")]
    pub legal_structure: models::TravelRuleIssuer,
    #[serde(rename = "incorporationCountry")]
    pub incorporation_country: models::TravelRuleIssuer,
    #[serde(rename = "businessNumber")]
    pub business_number: models::TravelRuleIssuer,
    #[serde(rename = "addressLine1")]
    pub address_line1: models::TravelRuleIssuer,
    #[serde(rename = "city")]
    pub city: models::TravelRuleIssuer,
    #[serde(rename = "country")]
    pub country: models::TravelRuleIssuer,
    #[serde(rename = "description")]
    pub description: models::TravelRuleIssuer,
}

impl TravelRuleIssuers {
    pub fn new(year_founded: models::TravelRuleIssuer, is_regulated: models::TravelRuleIssuer, regulatory_authorities: models::TravelRuleIssuer, name: models::TravelRuleIssuer, logo: models::TravelRuleIssuer, website: models::TravelRuleIssuer, legal_name: models::TravelRuleIssuer, legal_structure: models::TravelRuleIssuer, incorporation_country: models::TravelRuleIssuer, business_number: models::TravelRuleIssuer, address_line1: models::TravelRuleIssuer, city: models::TravelRuleIssuer, country: models::TravelRuleIssuer, description: models::TravelRuleIssuer) -> TravelRuleIssuers {
        TravelRuleIssuers {
            year_founded,
            is_regulated,
            regulatory_authorities,
            name,
            logo,
            website,
            legal_name,
            legal_structure,
            incorporation_country,
            business_number,
            address_line1,
            city,
            country,
            description,
        }
    }
}

