// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TravelRuleNaturalPersonNameIdentifier {
    #[serde(rename = "nameIdentifier", skip_serializing_if = "Option::is_none")]
    pub name_identifier: Option<Vec<models::TravelRuleNaturalNameIdentifier>>,
    #[serde(
        rename = "localNameIdentifier",
        skip_serializing_if = "Option::is_none"
    )]
    pub local_name_identifier: Option<Vec<models::TravelRuleNaturalNameIdentifier>>,
    #[serde(
        rename = "phoneticNameIdentifier",
        skip_serializing_if = "Option::is_none"
    )]
    pub phonetic_name_identifier: Option<Vec<models::TravelRuleNaturalNameIdentifier>>,
}

impl TravelRuleNaturalPersonNameIdentifier {
    pub fn new() -> TravelRuleNaturalPersonNameIdentifier {
        TravelRuleNaturalPersonNameIdentifier {
            name_identifier: None,
            local_name_identifier: None,
            phonetic_name_identifier: None,
        }
    }
}
