// Fireblocks API
//
// Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com)
//
// The version of the OpenAPI document: 1.8.0
// Contact: developers@fireblocks.com
// Generated by: https://openapi-generator.tech

use {
    crate::models,
    serde::{Deserialize, Serialize},
};

/// TravelRuleDateAndPlaceOfBirth : Represents the date and place of birth for a
/// natural person
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TravelRuleDateAndPlaceOfBirth {
    /// Date of birth. The value must be encrypted.
    #[serde(rename = "dateOfBirth", skip_serializing_if = "Option::is_none")]
    pub date_of_birth: Option<String>,
    /// Place of birth. The value must be encrypted.
    #[serde(rename = "placeOfBirth", skip_serializing_if = "Option::is_none")]
    pub place_of_birth: Option<String>,
}

impl TravelRuleDateAndPlaceOfBirth {
    /// Represents the date and place of birth for a natural person
    pub fn new() -> TravelRuleDateAndPlaceOfBirth {
        TravelRuleDateAndPlaceOfBirth {
            date_of_birth: None,
            place_of_birth: None,
        }
    }
}
