/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TravelRulePiiIvms {
    #[serde(rename = "fullName")]
    pub full_name: String,
    #[serde(rename = "dateOfBirth")]
    pub date_of_birth: String,
    #[serde(rename = "placeOfBirth")]
    pub place_of_birth: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "identificationNumber")]
    pub identification_number: String,
    #[serde(rename = "nationality")]
    pub nationality: String,
    #[serde(rename = "countryOfResidence")]
    pub country_of_residence: String,
    #[serde(rename = "taxIdentificationNumber")]
    pub tax_identification_number: String,
    #[serde(rename = "customerNumber")]
    pub customer_number: String,
}

impl TravelRulePiiIvms {
    pub fn new(full_name: String, date_of_birth: String, place_of_birth: String, address: String, identification_number: String, nationality: String, country_of_residence: String, tax_identification_number: String, customer_number: String) -> TravelRulePiiIvms {
        TravelRulePiiIvms {
            full_name,
            date_of_birth,
            place_of_birth,
            address,
            identification_number,
            nationality,
            country_of_residence,
            tax_identification_number,
            customer_number,
        }
    }
}

