/*
 * Fireblocks API
 *
 * Fireblocks provides a suite of applications to manage digital asset operations and a complete development platform to build your business on the blockchain.  - Visit our website for more information: [Fireblocks Website](https://fireblocks.com) - Visit our developer docs: [Fireblocks DevPortal](https://developers.fireblocks.com) 
 *
 * The version of the OpenAPI document: 1.8.0
 * Contact: developers@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnspentInput : A representation of an Unspent Transaction Output (UTXO). 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnspentInput {
    /// Transaction Hash
    #[serde(rename = "txHash", skip_serializing_if = "Option::is_none")]
    pub tx_hash: Option<String>,
    /// The UTXO index (vOut)
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index: Option<f64>,
}

impl UnspentInput {
    /// A representation of an Unspent Transaction Output (UTXO). 
    pub fn new() -> UnspentInput {
        UnspentInput {
            tx_hash: None,
            index: None,
        }
    }
}

