/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// XbSettlementCryptoAsset : - XLM_USDC_5F3T : USDC over Stellar network 
/// - XLM_USDC_5F3T : USDC over Stellar network 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum XbSettlementCryptoAsset {
    #[serde(rename = "XLM_USDC_5F3T")]
    XlmUsdc5F3T,
    #[serde(rename = "XLM")]
    Xlm,

}

impl std::fmt::Display for XbSettlementCryptoAsset {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::XlmUsdc5F3T => write!(f, "XLM_USDC_5F3T"),
            Self::Xlm => write!(f, "XLM"),
        }
    }
}

impl Default for XbSettlementCryptoAsset {
    fn default() -> XbSettlementCryptoAsset {
        Self::XlmUsdc5F3T
    }
}

