/*
 * Fireblocks API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.7.5
 * Contact: support@fireblocks.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct XbSettlementConfigStep {
    #[serde(rename = "stepType")]
    pub step_type: models::XbSettlementStepType,
    #[serde(rename = "accountId")]
    pub account_id: String,
}

impl XbSettlementConfigStep {
    pub fn new(step_type: models::XbSettlementStepType, account_id: String) -> XbSettlementConfigStep {
        XbSettlementConfigStep {
            step_type,
            account_id,
        }
    }
}

